name: GitHub Actions Cron sync this fork from upstream
# on push can specify branch
on:
  schedule:
  - cron: "0/30 * * * *"
  workflow_dispatch:

jobs:
  Sync-Fork-From-Upstream:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Pull Upstream
        uses: The-OpenROAD-Project/actions/upstream_sync@main
        
        # main notes
        # don't use git merge but instead git reset unless merging a PR
        # don't use pygithub in action but use urllib3 instead directly with json python lib
        # on push support branch specifier
        # steal actions from others // fork them to my own org if worried about disappearing
        # make security repo public
        
