name: Check that OK files are up to date

on:
  pull_request:

jobs:
  No-Diffs-In-Ok-Files:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check ok files
        run: |
          set +e
          grep --include="*.ok" -Rn "Differences found "
          if [[ "$?" == "0" ]]; then
            exit 1
          fi
