name: clang-tidy-review

on:
  pull_request:
    branches:
      - master

jobs:
  Clang-Tidy:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
      - name: ClangTidy Gen
        uses: The-OpenROAD-Project/clang-tidy-review@master
        id: review
        with:
          clang_tidy_version: 19
          build_dir: "./build"
          cmake_command: cmake . -B build -D Boost_DIR=/usr/local/lib/cmake/Boost-1.89.0
          config_file: ".clang-tidy"
          exclude: "*/codeGenerator/templates/*,third-party/*,test/orfs/*"
          split_workflow: true
          apt_packages: libomp-15-dev,libfl-dev,libyaml-cpp-dev
      - uses: The-OpenROAD-Project/clang-tidy-review/upload@master
        id: upload-review
      - name: Correct Build Directory Ownership
        if: always()
        run: |
          echo "Attempting to change ownership of ${{ github.workspace }} back to runner user..."
          sudo /usr/bin/chown -R $(id -u):$(id -g) ${{ github.workspace }}
          echo "Ownership change attempt finished."
        shell: bash
      - if: steps.review.outputs.total_comments > 0
        run: |
          echo "Pending review comments. Please resolve all comments before merging."
          exit 1
