name: GitHub Actions Cron sync this fork from upstream
on:
  schedule:
  - cron: "0/30 * * * *"
  workflow_dispatch:

jobs:
  Sync-Fork-From-Upstream:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "This job's status is ${{ job.status }}."
      - run: ls
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git switch master; git status
      - run: git remote add upstream https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git
      - run: git fetch upstream master
      - run: git merge upstream/master --allow-unrelated-histories
      - run: git push
