name: Labelled Ready to Sync Public
on:
  pull_request:
    types: [labeled]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'The-OpenROAD-Project-private' && github.event.label.name == 'Ready To Sync Public'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            ref: ${{github.event.pull_request.head.ref}}
            fetch-depth: 0
            token: ${{ secrets.GITHUBPUBLICREPOTOKEN }}
      
      - name: run security scan
        uses: The-OpenROAD-Project/actions/security_scan_on_push@main
        
      - name: add remote
        run: git remote add staging https://github.com/The-OpenROAD-Project-staging/OpenROAD.git
      - name: print remotes
        run: git remote -v
      - name: git status
        run: git status
      - name: Current label
        run: echo ${{github.event.label.name}}
      - name: pr info
        run: echo ${{toJson(github.event.pull_request.head.ref)}} 
      #- name: Unshallow
      #  run: git fetch --unshallow
      - name: push to staging
        run: git push staging

          

        
